apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-generator
  labels:
    app: generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: generator
  template:
    metadata:
      labels:
        app: generator
    spec:
      containers:
        - name: generator
          image: "{{ .Values.generator.image.repository }}:{{ .Values.generator.image.tag }}"
          imagePullPolicy: {{ .Values.generator.image.pullPolicy }}
          env:
            - name: KAFKA_BROKER
              value: "{{ .Release.Name }}-kafka:9092"
            - name: TRANSACTIONS_TOPIC
              value: "transactions"
